# Generated by Django 5.2.14 on 2026-05-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("response", "0009_userresponse_alternatemobileno"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="prebookOfflineYearbook",
            field=models.CharField(default="no", max_length=3),
        ),
    ]
