# Generated by Django 5.2.14 on 2026-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("response", "0010_userresponse_prebookofflineyearbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="pincode",
            field=models.CharField(default="", max_length=10),
        ),
    ]
